### ISSUE TITLE
updateできない [BUG]

### ISSUE THREAD

**Issue by anondiscord-noname** [Chinachu/Mirakurun#113]
- `uname -srvmo`: `Linux 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux`
- `cat /etc/issue`: `Raspbian GNU/Linux 11 \n \l`
- `cat /proc/cpuinfo | grep name -m 1`: `ARMv7 Processor rev 3 (v7l)`
- Version of Mirakurun: `3.9.0-beta.22`
- Version of Node: `v16.13.1`
- Version of NPM: `8.1.2`

**For UI related issue:**<br>
**UI に関連した問題:**

- Client OS: macOS Big Sur 11.5.2
- Browser: Google Chrome 95.0.4638.69

### Issue (不具合の内容)

`./chinachu update` を行うと、失敗します
エラー内容
```
node:internal/fs/utils:879
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (16158)
    at Object.writeFileSync (node:fs:2146:5)
    at createPidFile (/home/pi/chinachu/app-scheduler.js:96:5)
    at /home/pi/chinachu/app-scheduler.js:670:3
    at isRunning (/home/pi/chinachu/app-scheduler.js:120:3)
    at Object.<anonymous> (/home/pi/chinachu/app-scheduler.js:664:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
failed somehow
```

### Expected (期待される動作)

updateを正常に実行

**Comment by kanreisa** [comment]
ここは Mirakurun のリポジトリですので Chinachu についての質問は Discord の question 等で聞いてみてください。
