### ISSUE TITLE
アップデート失敗&起動不可

### ISSUE THREAD

**Issue by KawakawaRitsuki** [Chinachu/Mirakurun#22]
### Environment
* Version of Mirakurun: `2.1.0`
* Version of Node: `v6.10.3`
* Version of NPM: `3.10.10`
* Platform: Cent OS 7
* Architecture: x64

### Issue
Mirakurun UIからアップデートのAPIを叩いたら再起動後、起動せず。
アップデート失敗。その後起動不可に。
コマンドラインからのアップデートは試してないです（UIのため）。

```
Error: Cannot find module 'promise-queue'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/mirakurun/lib/Mirakurun/Mirakurun/queue.ts:18:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by kanreisa** [comment]
```
sudo npm install npm@4 -g
sudo npm install pm2@2 -g
sudo npm install mirakurun@2.5.4 -g --unsafe --production
```
してから UI からまたトライしてみてください。

**Comment by KawakawaRitsuki** [comment]
おお！行けました！ありがとうございます！
原因はnpmのバージョンが低かったということですかね。

PM2のバージョンがout of dateになったんですがこれは更新しても良いんでしょうか。

**Comment by kanreisa** [comment]
PM2は録画していない時にでも sudo pm2 update して頂ければOKです

**Comment by KawakawaRitsuki** [comment]
分かりました！ご丁寧にありがとうございます！
