### ISSUE TITLE
 failed on B_CAS_CARD::init() : code=-3と書かれたエラー

### ISSUE THREAD

**Issue by Marron0421** [Chinachu/Mirakurun#52]
### Issue
...
```
[TAILING] Tailing last 15 lines for [mirakurun-server] process (change the value with --lines option)
/usr/local/var/log/mirakurun.stderr.log last 15 lines:
3|mirakuru | { Error: write EPIPE
3|mirakuru |     at WriteWrap.afterWrite (net.js:779:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
3|mirakuru | error - failed on B_CAS_CARD::init() : code=-3
3|mirakuru | { Error: write EPIPE
3|mirakuru |     at WriteWrap.afterWrite (net.js:779:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
3|mirakuru | error - failed on B_CAS_CARD::init() : code=-3
3|mirakuru | { Error: write EPIPE
3|mirakuru |     at WriteWrap.afterWrite (net.js:779:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
3|mirakuru | error - failed on B_CAS_CARD::init() : code=-3
3|mirakuru | { Error: write EPIPE
3|mirakuru |     at WriteWrap.afterWrite (net.js:779:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
3|mirakuru | error - failed on B_CAS_CARD::init() : code=-3
3|mirakuru | { Error: write EPIPE
3|mirakuru |     at WriteWrap.afterWrite (net.js:779:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
3|mirakuru | error - failed on B_CAS_CARD::init() : code=-3
```
表題のようにmirakurun log serverを実行し、ログを見てみるとこのようなエラーが発生してしまいます。

EPGStationを使用し、録画は正常に成功するのですが、ライブ視聴で出来ない状態です

**Comment by kanreisa** [comment]
Mirakurun が出力しているエラーではありません。
エラーの内容を確認してください。

また、[Issue Template](https://github.com/Chinachu/Mirakurun/blob/master/.github/ISSUE_TEMPLATE.md) は削除せずに埋めてください。
Reopen する場合は [こちら](https://github.com/Chinachu/Mirakurun/blob/master/.github/CONTRIBUTING.md#report-an-issue) をよくお読みになり、 Issue Template を埋めてください。
