### ISSUE TITLE
RaspberryPi3に正しくインストール・設定できない

### ISSUE THREAD

**Issue by stu2005** [Chinachu/Mirakurun#63]
### Environment
* Version of Mirakurun: `2.13.0`
* Version of Node: `v12.13.1`
* Version of NPM: `6.12.1`
* Platform: Raspbian buster

### Issue
上記の環境にてmirakurunをインストールしようと試みましたが、下記のエラーログが出力されて各種設定がうまくできません。
```
0|mirakuru |     '    ^'
0|mirakuru | }
0|mirakuru | YAMLException: end of the stream or a document separator is expected at line 40, column 1:
0|mirakuru |     types:
0|mirakuru |     ^
0|mirakuru |     at generateError (/usr/local/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
0|mirakuru |     at throwError (/usr/local/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
0|mirakuru |     at readDocument (/usr/local/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:1539:5)
0|mirakuru |     at loadDocuments (/usr/local/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
0|mirakuru |     at load (/usr/local/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
0|mirakuru |     at Object.safeLoad (/usr/local/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:1618:10)
0|mirakuru |     at load (/usr/local/lib/node_modules/mirakurun/lib/Mirakurun/Mirakurun/config.ts:114:17)
0|mirakuru |     at Object.loadTuners (/usr/local/lib/node_modules/mirakurun/lib/Mirakurun/Mirakurun/config.ts:95:12)
0|mirakuru |     at Object.<anonymous> (/usr/local/lib/node_modules/mirakurun/lib/server.ts:56:26)
0|mirakuru |     at Module._compile (internal/modules/cjs/loader.js:959:30)
```
これらのエラーを解消する方法を教えていただけますでしょうか?

...

**Comment by kanreisa** [comment]
設定ファイルの [YAML](https://ja.wikipedia.org/wiki/YAML) 書式が間違っているのではないでしょうか。

**Comment by stu2005** [comment]
ありがとうございます。解決しました。
