### ISSUE TITLE
Muninプラグインの機能不全

### ISSUE THREAD

**Issue by R-Django** [Chinachu/Mirakurun#99]
### Environment
* Version of Mirakurun: `3.6.0`
* Version of Node: `v10.18.1`
* Version of NPM: `6.14.13`
* Platform: CentOS Linux release 7.7.1908 (Core)

### Issue

Mirakurun を 3.6.0 へアップデート後にMuninプラグインが動作しなくなりました。
下記は munin-run の実行結果の一部です。

`# munin-run --debug mirakurun_status
/usr/lib/node_modules/mirakurun/node_modules/js-yaml/index.js:10
    throw new Error('Function yaml.' + from + ' is removed in js-yaml 4. ' +
    ^

Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
    at Object.safeLoad (/usr/lib/node_modules/mirakurun/node_modules/js-yaml/index.js:10:11)
    at Object.<anonymous> (/usr/lib/node_modules/mirakurun/bin/munin-plugins/mirakurun_status.js:45:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)`

/usr/lib/node_modules/mirakurun/bin/munin-plugins/mirakurun_status.js の45行目を "yaml.safeLoad" から "yaml.load" へ変更し、munin-nodeを再起動する事で監視データを問題無く取得できるようになりました。

一応、ご報告まで。

**Comment by kanreisa** [comment]
@R-Django 
こんにちは
察するにこれはバグかと思います。
まだ見れていない間にクローズされてしまったようですが、
どんな状況でしょうか？

**Comment by kanreisa** [comment]
munin-plugins についてですが、私が利用を辞めてしまった事もあり、js-yaml の変更を見逃していました。
munin-plugins は次のバージョンで削除し、代わりに別のリポジトリで配布したいと思います。
どうぞよろしくお願いいたします。

**Comment by R-Django** [comment]
個人の範疇で問題の解決に至れたので、
他に困っている方がおられるかもと取敢えずの情報の記録として
さっさとCloseしてしましました。 御免なさい。

>どんな状況でしょうか？
先に触れられた通り”Function yaml.safeLoad is removed in js-yaml 4.”とありますので、
js-yaml というもののバージョン管理に依るもののようですね。

>munin-plugins は次のバージョンで削除し、代わりに別のリポジトリで配布したいと思います。

了解です。ありがとうございました。

**Comment by kanreisa** [comment]
いえいえご報告ありがとうございます。
おかげで気づけました。
今後ともよろしくお願いいたします
